<a href="https://colab.research.google.com/github/Nico88-Vs/Tenser_course/blob/main/00_TenserFlow_fondamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Import Tenserflow

import tensorflow as tf


Key points :
* introduction  to tensor
* getting info from tensor
* manipulating tensor
* using @tf.funcion (speeding up python funcion)
* using gpu or tpu in tensorflow
  

In [2]:
print(tf.__version__)

2.12.0


In [3]:
# creating tensor with tf.constant() >>> arlady existing in pckes  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> SCALAR
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# check the number of dimension (tensor) .ndim
scalar.ndim

0

In [5]:
#creating a vector >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> VECTOR
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# check dimension of vector
vector.ndim

1

In [7]:
from numpy.matrixlib.defmatrix import matrix
# create a metrix (piu di una dimensione)
matrix = tf.constant([[10,7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
#create another metrix >> dot for float  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> METRIX
another_matrix = tf.constant([[10.,2.], [11.,12.],[13.,11.]], dtype=tf.float16) # d type specicato (int32 defoult precision)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  2.],
       [11., 12.],
       [13., 11.]], dtype=float16)>

In [10]:
# quant e la dimensione di another ??? 2 >>> numero di elemnti nella shape!!! >>>> row culoms and more ..... numero delle dimensioni
another_matrix.ndim

2

In [11]:
#creamo un vero tensor >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> TENSOR
tensor = tf.constant([[[1,2,3,], [1,2,3]],
  [[1,2,3],[1,2,3]],
  [[1,2,3],[1,2,3]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]], dtype=int32)>

In [12]:
tensor.ndim

3

RECAP:

*   Scalar : grandezza scalare
*   Vector : grandezza bi_dimensionale ( speed with direction)
*   Metrix : array bi_dimensionale
*   Tensor : n-dimentional array



### Utilizzo di variabile anziche costante 'tf.variable'

In [13]:
# Creating a changable tensor
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor , unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# try to change changable tensor using index
# changable_tensor[0] = 7 ERROR
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
# try to change Un_changable tensor using index
# unchangable_tensor[0] = 7 ERROR
# unchangable_tensor[0].assign(7) >>>>> non esiste ASSIGN
unchangable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

### creating random tensor
random tensor is a tansor of some arbitrary size wich contain random numbers

In [16]:
# used at beginning to appresentate first output CREATION >>>>>> seed collega un riferimento ... X ....
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape = (3,2)) # normal distribution
random_2 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_2 = random_2.normal(shape = (3,2)) # normal distribution
random_1 == random_2


<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of elemnt in a tensor

In [17]:
# to avoid NN miss learn by a starting sequence
not_shufled = tf.constant([[10,7],[11,8],[5,6]])
# shuffle our tensor
tf.random.shuffle(not_shufled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  6],
       [11,  8],
       [10,  7]], dtype=int32)>

In [18]:
from operator import not_
# if we set a seed shuffle seems referred to a "seme" therefore never change
tf.random.set_seed(42) #gloal seed as envoirment variable in random generation
tf.random.shuffle(not_shufled, seed=42) # operation seed  >>> referation seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [11,  8],
       [ 5,  6]], dtype=int32)>

### Exercise ... test shuffle on random tensor constant in order to get how seed works

In [19]:
tens_one = tf.constant([[1,2,4],[1,2,3]])
tens_tow = tf.constant([[1,2],[3,4],[5,6]])
tens_three = tf.constant([[[1,22],[2,33]],[[3,44],[5,66]]])

seed = tf.random.set_seed(18)

seed_one = 1
seed_tow = 2
seed_three = 3

In [20]:
# menage tensors with different seeds

tf.random.shuffle(tens_one, seed = seed_one)
tf.random.shuffle(tens_tow, seed = seed_tow)
tf.random.shuffle(tens_three, seed = seed_three)
#tens_one, tens_tow, tens_three  >>>> OUTPUT SENZA SHUFFLE , LE ISTANZE DI TENSOR NON SONO STATE SOVRASCRITTE

# RIPROVO UTILIZZANDO NUOVE VARIABILI
x = tf.random.shuffle(tens_one, seed = seed_one)
y = tf.random.shuffle(tens_tow, seed = seed_tow)
z = tf.random.shuffle(tens_three, seed = seed_three)
x,y,z

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [1, 2, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [5, 6],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[ 1, 22],
         [ 2, 33]],
 
        [[ 3, 44],
         [ 5, 66]]], dtype=int32)>)

In [21]:
# Notato che sono stati invertivi i livelli superiori !!!!! non toccati gli inferiori

# modifico i seed
seed_one = 11
seed_tow = 22
seed_three = 33

x = tf.random.shuffle(tens_one, seed = seed_one)
y = tf.random.shuffle(tens_tow, seed = seed_tow)
z = tf.random.shuffle(tens_three, seed = seed_three)
x,y,z

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [1, 2, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 4],
        [5, 6],
        [1, 2]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[ 3, 44],
         [ 5, 66]],
 
        [[ 1, 22],
         [ 2, 33]]], dtype=int32)>)

In [22]:
# nothig changed with dubled compile side seed changing
# modifico il server-side seed

seed = tf.random.set_seed(110)

seed_one = 33
seed_tow = 22
seed_three = 11

x = tf.random.shuffle(tens_one, seed = seed_one)
y = tf.random.shuffle(tens_tow, seed = seed_tow)
z = tf.random.shuffle(tens_three, seed = seed_three)
x,y,z

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 4],
        [1, 2, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 4],
        [1, 2],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[ 1, 22],
         [ 2, 33]],
 
        [[ 3, 44],
         [ 5, 66]]], dtype=int32)>)

In [23]:
### otherway  to make tensor


In [24]:
# create a tensor of all 1 ... setting a shape
tf.ones(shape=[10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [25]:
# create tensor of all 0
tf.zeros([11,3])

<tf.Tensor: shape=(11, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [26]:
# turn numpy_arrays into tensors
# tensor can be run much faster in a gpu
# Capital for matrix or tensor
# non_capital for vector

import numpy as np

numpay_A = np.arange(1,25, dtype=np.int32)
numpay_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [27]:
# trasformo in un tensore
A = tf.constant(numpay_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [28]:
# cambio la forma
B = tf.constant(numpay_A, shape =(2,3,4))
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [29]:
#errore se non corrispondono tutti gli elementi
#C = tf.constant(numpay_A, shape =(2,3,5))
#C

In [30]:
# Run  before from runtime in order to get all the instances

### getting info from tensor
* Shape >>>> Lengt of each dimension
* Rank >>> number of tensor's dimensions : scalar 0; vector 1; matrix 2;.....
* Axis or dimension >>>> A paarticular dimension tensor >>> tensor[0], tens[:,1]
* Size >> number of item in tensor tf.size(tensor)

In [31]:
# creating a rank 4 tensor
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor     #>>>> seems that da sinistra a dx generico particolare

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
# getting a specifica dimention from a tensor  >>>> tensor[i] ; tensor[:,i]
# sembra che prenda la dimensione specifica indicizzata , l'istanza di quella dimensione
dim_1 = rank_4_tensor[1]
dim_2 = rank_4_tensor[:,1]
dim_1, dim_2

(<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
 array([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
 array([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=float32)>)

In [33]:
# getting all info
rank_4_tensor.ndim, rank_4_tensor.shape, tf.size(rank_4_tensor)

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [34]:
# 2*3*4*5 == 120


#get various attribute of our tensor
print("Datatype of Tensors : ", rank_4_tensor.dtype)
print("Rank : ", rank_4_tensor.ndim)
print("Shape of Tensors : ", rank_4_tensor.shape)
print("Element in x axis : ", rank_4_tensor.shape[0])
print("Element in last axis : ", rank_4_tensor.shape[-1]) #bello questo meno uno by python
print("Size of Tensors : ", tf.size(rank_4_tensor))
print("Size of Tensors as numpy : ", tf.size(rank_4_tensor).numpy())


Datatype of Tensors :  <dtype: 'float32'>
Rank :  4
Shape of Tensors :  (2, 3, 4, 5)
Element in x axis :  2
Element in last axis :  5
Size of Tensors :  tf.Tensor(120, shape=(), dtype=int32)
Size of Tensors as numpy :  120


In [35]:
# get first  tow element of each dimension by python list

# getting from py list
some_list = [1,2,3,4]
some_list[:2]

#the tensor
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [36]:
#get the fir elemnt for each dimention except the final one

rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

### re_shaping

In [37]:
rank2_tensor = tf.constant([[10,7],[1,3]])

# Add extra dimention  >>>>> ..., after evry axis

rank3_tensor = rank2_tensor[..., tf.newaxis]
rank4_ten = tf.expand_dims(rank3_tensor, -1) # 0 per la prima ; -1 per la fine

rank3_tensor, rank4_ten

(<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 1],
         [ 3]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
 array([[[[10]],
 
         [[ 7]]],
 
 
        [[[ 1]],
 
         [[ 3]]]], dtype=int32)>)

###Manipulating Tensor ___ tensors operations

In [38]:
### Basic operations "+, - , *, /"

In [39]:
tensor = tf.constant([[10,7],[1,3]])
tensor + 10  # Adding 10 to each item

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [11, 13]], dtype=int32)>

In [40]:
# guessing evrione else will work equivalently
tf.multiply(tensor, 10) #>>> faster then basic operation
tf.divide(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.1, 0.3]])>

In [41]:
# matrix moltiplication
#dot product deve esserci corrispondenza nel numero di elementi che vengono poi moltiplicati uno per uno sommando i prodotti

tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[107,  91],
       [ 13,  16]], dtype=int32)>

In [42]:
#dot product with different shape

# rules : ineer dimention must match
#       : the resoulting matrix has the shape of outer dimention 3x3 3x2

y = tf.constant([[10,7],[1,3],[5,4]])
x = tf.constant([[10,7],[1,3],[5,4]])

# Let s change the shape of Y
yreshaped = tf.reshape(y, shape=(2,3))
yreshaped.shape


TensorShape([2, 3])

In [43]:
tf.matmul(x, yreshaped)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[121, 105,  38],
       [ 19,  22,  13],
       [ 62,  55,  21]], dtype=int32)>

In [44]:
# transpose sostituisce colonne con righe
x , tf.transpose(x)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 1,  3],
        [ 5,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10,  1,  5],
        [ 7,  3,  4]], dtype=int32)>)

In [45]:
# reshape sposta gli elementi
x, tf.reshape(x,(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 1,  3],
        [ 5,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10,  7,  1],
        [ 3,  5,  4]], dtype=int32)>)

In [46]:
# tf.tensordot(,, axis) >>> chiede su quale asse eseguire la moltiplicazione

# Changing dataType >>> reducing precision from float32(bit) to float(16)

D = tf.cast(x, dtype=np.float16)
x.dtype, D.dtype

(tf.int32, tf.float16)

### Aggregating tensors
Aggregating tensors = condensing them from multiple values down to a smaller ammount of values

In [47]:
# get the absolute values
D = tf.constant([-7,-10])

Dabs = tf.abs(D)
Dabs

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

# Some forms of aggregations
* get minimum
* get maximum
* get the mean of a tensor
* get the sum of a tensor


In [48]:
# new tensor

E = tf.constant(np.random.randint(0,100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 6, 78, 27, 68, 52, 53, 77, 14, 92, 91, 38, 54, 83, 13,  9, 80, 87,
       61, 12, 40, 61, 43, 11, 99, 69, 48, 26, 32,  5, 75, 58,  3, 73,  8,
       13, 23,  2, 33, 89, 79, 87, 59, 79, 81, 40, 40, 71, 67, 57, 81])>

In [49]:
# find min
tf.reduce_min(E)

# find stdv
import tensorflow_probability as tfp


In [50]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=842>

In [51]:
# standar deviation
tfp.stats.stddev(tf.cast(E, dtype=tf.float32)), tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

(<tf.Tensor: shape=(), dtype=float32, numpy=29.00442>,
 <tf.Tensor: shape=(), dtype=float32, numpy=29.00442>)

In [52]:
# find the positional maximul and minimul >>> per sceglier gli output a maggiore probabilita

# seleziono il seed per riprodurre un output specifico

tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [53]:
#ottengo l'indice del massimo valore
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [54]:
# ottenere il valore
F[tf.argmax(F)], tf.math.reduce_max(F)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [55]:
# Test con una matrice
y_mat = tf.constant([[10,7],[1,18],[5,4]])

tf.argmax(y_mat)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 1])>

### squeezing tensor
* uniforming by removing each dimentions

In [56]:
X = tf.constant(tf.random.uniform(shape=[72]), shape=(1,3,4,6))
X

<tf.Tensor: shape=(1, 3, 4, 6), dtype=float32, numpy=
array([[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
          0.89256823],
         [0.94674826, 0.7493341 , 0.34925628, 0.54718256, 0.26160395,
          0.69734323],
         [0.11962581, 0.53484344, 0.7148968 , 0.87501776, 0.33967495,
          0.17377627],
         [0.4418521 , 0.9008261 , 0.13803864, 0.12217975, 0.5754491 ,
          0.9417181 ]],

        [[0.9186585 , 0.59708476, 0.6109482 , 0.82086265, 0.83269787,
          0.8915849 ],
         [0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
          0.908944  ],
         [0.40900218, 0.8765154 , 0.53890026, 0.42733097, 0.401173  ,
          0.66623247],
         [0.16348064, 0.18220246, 0.97040176, 0.06139731, 0.53034747,
          0.9869994 ]],

        [[0.4746945 , 0.8646754 , 0.20301068, 0.11448455, 0.35100245,
          0.68227184],
         [0.18108869, 0.8163481 , 0.65651655, 0.9258256 , 0.2391715 ,
          0.8365958 ],
         [0.

In [57]:
X_sqeezed = tf.squeeze(X)
X_sqeezed, X_sqeezed.shape # elimina le dimensioni aventi un solo argomento

(<tf.Tensor: shape=(3, 4, 6), dtype=float32, numpy=
 array([[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
          0.89256823],
         [0.94674826, 0.7493341 , 0.34925628, 0.54718256, 0.26160395,
          0.69734323],
         [0.11962581, 0.53484344, 0.7148968 , 0.87501776, 0.33967495,
          0.17377627],
         [0.4418521 , 0.9008261 , 0.13803864, 0.12217975, 0.5754491 ,
          0.9417181 ]],
 
        [[0.9186585 , 0.59708476, 0.6109482 , 0.82086265, 0.83269787,
          0.8915849 ],
         [0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
          0.908944  ],
         [0.40900218, 0.8765154 , 0.53890026, 0.42733097, 0.401173  ,
          0.66623247],
         [0.16348064, 0.18220246, 0.97040176, 0.06139731, 0.53034747,
          0.9869994 ]],
 
        [[0.4746945 , 0.8646754 , 0.20301068, 0.11448455, 0.35100245,
          0.68227184],
         [0.18108869, 0.8163481 , 0.65651655, 0.9258256 , 0.2391715 ,
          0.8365958 ],
         [0.

In [58]:
# One hot encoding >> preparing data
### ASSEGNAZIONE DI UN VALORE COME RAPPRESANTAZIONE DI UNO SPECIFICO ITEM (OGGETTO)

# CREATING A LIST
lista_cazzo = [9,2,3,8]
# DEFINISCO LA PROFONDITA PER POTER AVERE UNA LISTA DI VALORI PER OGNI ELEMENTO CHE VOGLIO CODIFICARE
depth = 4
# IN FINE CODIFICO
tf.one_hot(lista_cazzo, depth=depth)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [59]:
# specificare un valore per on_hot encoding
tf.one_hot(lista_cazzo, depth=10, on_value=3, off_value=4)

<tf.Tensor: shape=(4, 10), dtype=int32, numpy=
array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 3],
       [4, 4, 3, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 3, 4]], dtype=int32)>

# depth e la profondita del campione dei valori di encoding

###Finding Access to gpu

In [60]:
#returning list of physical devices list
tf.config.list_physical_devices(), tf.config.list_physical_devices("GPU")

([PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
  PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')],
 [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')])

In [61]:
# check gp detail and CUDA status
!nvidia-smi

Sat Jul  1 17:54:24 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P0    29W /  70W |    389MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### Regression Problems
#relazione fra variabili indipendenti e dipendenti
* output variablie >>> predizione
* variabili indipendenti >>> caratteristiche della variabile

### Input / Output in a regression model
**